name: test

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "**.zig"
      - "**.zon"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "**.zig"
      - "**.zon"

jobs:
  test:
    strategy:
      matrix:
        include:
          - zig-version: 0.15.0-dev.1149+4e6a04929

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Grab Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Tests master
        run: |
          zig build test --summary all

      - name: Linux modules
        run: |
          zig build check -Dtarget=x86_64-linux-gnu -Doptimize=ReleaseFast

      - name: macOS modules
        run: |
          zig build check -Dtarget=aarch64-macos-none -Doptimize=ReleaseFast

      - name: Windows modules
        run: |
          zig build check -Dtarget=x86_64-windows-msvc -Doptimize=ReleaseFast

      - name: WebAssembly modules
        run: |
          zig build check -Dtarget=wasm32-freestanding -Doptimize=ReleaseSmall
